name: Backup Routine
on:
  push:
    branches:
      - feature/v2  # TODO: adjust
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  backup-dataset:
    runs-on: ubuntu-18.04
    name: Backup Sanity Data
    strategy:
      matrix:
        dataset: [ "development", "production" ]
    steps:
      - name: set output file
        id: env
        run: echo "::set-output name=filename::$(date +%Y-%m-%d)-${{ matrix.dataset}}.tar.gz"

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install sanity cli
        run: |
          npm install --global sanity@dev-preview wrangler@latest

      - name: export dataset
        run: |
          set -e

          cat << EOF > .env
          SANITY_STUDIO_API_PROJECT_ID=${{ secrets.SANITY_STUDIO_API_PROJECT_ID }}
          EOF

          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" \
            sanity dataset export "${{ matrix.dataset}}" "${{ steps.env.outputs.filename }}"

      - name: upload backup.tar.gz
        run: |
          wrangler r2 object put "${{ github.repository	}}/${{ env.filename }}" -f ${{ steps.env.outputs.filename }}
        working-directory: ./studio
